<html>


<?php
$input_category = $_POST["input_category"];
$input = $_POST["input"];

$oldldpath = getenv('LD_LIBRARY_PATH');
putenv("LD_LIBRARY_PATH=");

shell_exec("WORKSPACE=`pwd`");

if ( strcmp($input_category, "topic") == 0) {

   function on_error()
   {
   echo "<b> Input Error ! </b>";
   echo "<br> <b>Example:</b> topic:nss_high </br>";
   echo "click <a href='gerrit_tracker.html'> here </a> to retry ";
   exit();
   }

   if (substr($input, 0, 6) != "topic:") {
   on_error();
   } 

   $input_array = str_split("$input");
   foreach ($input_array as $value) {
   if ($value == " ") {
   on_error();
   }
   }



   //on_success
   // create a local request file. remove whitespaces if any.
   $local_tmp_file = shell_exec("mktemp --tmpdir=`pwd` --suffix='.txt' -p $input_category");
   shell_exec("chmod 777 $local_tmp_file");
   shell_exec("echo $input >> $local_tmp_file");
   $local_tmp_file = preg_replace('/\s+/', '', $local_tmp_file);

   // replace the .txt extension to .html to view the output file.
   // the below html file is generated by gerrit_tracker_poll.py
   $output_html_file = str_replace(".txt", ".html", $local_tmp_file);

   // opens the output file once it is generated
   while (!file_exists($output_html_file)) sleep(1);
   echo "<script>";
   echo "window.open('$output_html_file','_self')";
   echo "</script>";


}
putenv("LD_LIBRARY_PATH=$oldldpath");


?>
</html>
